# TiKV Configuration

# log level: trace, debug, info, warn, error, off.
 log-level = "off"
# file to store log, write to stderr if it's empty.
# log-file = ""

[server]
# set attributes about this server, e.g. { zone = "us-west-1", disk = "ssd" }.
# labels = {}

[coprocessor]
# When it is true, it will try to split a region with table prefix if
# that region crosses tables. It is recommended to turn off this option
# if there will be a large number of tables created.
# split-region-on-table = true
# When the region's size exceeds region-max-size, we will split the region
# into two which the left region's size will be region-split-size or a little
# bit smaller.
 region-max-size = "28MB"
 region-split-size = "14MB"
